### ISSUE TITLE
Prefix not stored

### ISSUE THREAD

**Issue by adrianoalfaro** [JDI-company/Smart-Phone-for-Ninja-Forms#1]
Hello! I’m using your plugin on this page https://www.pdgboattours.it/#book

The prefix won’t save/show in the Ninja Forms Submission page. Is it a bug or a config problem? Any recommendation? Thank you so much!

**Comment by yaroslav-borodii** [comment]
Dear Adriano Alfaro,

I am writing to express my sincere gratitude for taking the time to report the bug/issue you encountered while using our software. Your contribution to the improvement of our product is truly invaluable, and we appreciate your effort in helping us ensure that our software is of the highest quality.

We understand that identifying and reporting bugs/ issues can be a time-consuming and challenging process, and we are grateful that you chose to bring this matter to our attention. Your thoroughness and attention to detail in reporting the bug/issue have helped us to identify and resolve the problem quickly, which will ultimately benefit all of our users.

We at JDI.company are committed to delivering a product that meets the needs and expectations of our users, and your contribution has brought us one step closer to achieving that goal. We hope that you will continue to use our software and provide us with your valuable feedback.

Could you please provide us some additional information about your environment?
For example:
1. What version of WordPress are you using?
2. What version of PHP are you using?
3. Screenshots of the issue?

--
Best regards,

Yaroslav Borodii

**Comment by adrianoalfaro** [comment]
Hi! Just wondering if you have an ETA for this fix. Thanks a lot!

**Comment by yaroslav-borodii** [comment]
Hello, @adrianoalfaro!
We are working on it, we will try to finish it by Wednesday

--
Best regards,

Yaroslav Borodii

**Comment by adrianoalfaro** [comment]
Hi! Were you able to find the bug? Let me know if I can help testing the new release! Thanks and have a good day :)

**Comment by yaroslav-borodii** [comment]
Dear @adrianoalfaro,

We have fantastic news to share! The long-awaited update for our plugin is finally here, and we sincerely apologize for the extended wait. Our development team has been working diligently to address all the reported issues and make significant improvements.

To experience the full benefits of the updated plugin, we highly recommend downloading the latest version. It not only resolves the previous issues but also introduces exciting new features that we're sure you'll love.

Now, for a lighthearted moment during this long journey, here's a joke for you:

Why did the plugin take so long to update?

Because it wanted to make sure every line of code was perfectly cooked!

We hope this joke brings a smile to your face and lightens the wait you endured. We appreciate your patience and understanding throughout this process. If you encounter any difficulties or have any questions during the update, our dedicated support team is always ready to assist you.

Thank you for your unwavering support, and we're thrilled to have you as a valued user of our plugin. Enjoy the new and improved version!

--
Best regards,
Yaroslav Borodii
