### ISSUE TITLE
Responsive issue in Elementor

### ISSUE THREAD

**Issue by patrick1980ch** [JDI-company/Smart-Phone-for-Ninja-Forms#3]
Hi there, 

I added the smart phone field in my Elementor built website. It works without problem in desktop but when I checked in my mobile phone it's just showing the phone filed and the country code and flags are not showing. So I installed the plugin in a different website , that I built with WP page bakery and it is working without any issue  in mobile. Could you please check that issue and let me know how to sort out this issue.?  I have attached the screenshot from my mobile, please have a look. Thanks in advance

![Screenshot_2023-04-14-00-31-45](https://user-images.githubusercontent.com/130704100/231876688-a00b9fb4-170f-4100-a51d-d22a768a6bab.jpg)

**Comment by yaroslav-borodii** [comment]
Dear [patrick1980ch](https://github.com/patrick1980ch),

I am writing to express my sincere gratitude for taking the time to report the bug/issue you encountered while using our software. Your contribution to the improvement of our product is truly invaluable, and we appreciate your effort in helping us ensure that our software is of the highest quality.

We understand that identifying and reporting bugs/ issues can be a time-consuming and challenging process, and we are grateful that you chose to bring this matter to our attention. Your thoroughness and attention to detail in reporting the bug/issue have helped us to identify and resolve the problem quickly, which will ultimately benefit all of our users.

We at JDI.company are committed to delivering a product that meets the needs and expectations of our users, and your contribution has brought us one step closer to achieving that goal. We hope that you will continue to use our software and provide us with your valuable feedback.

Could you please provide us some additional information about your environment?
For example:

What version of WordPress are you using?
What version of PHP are you using?
What version of Elementor are you using?
--
Best regards,

Yaroslav Borodii

**Comment by yaroslav-borodii** [comment]
Dear @patrick1980ch,

We have fantastic news to share! The long-awaited update for our plugin is finally here, and we sincerely apologize for the extended wait. Our development team has been working diligently to address all the reported issues and make significant improvements.

To experience the full benefits of the updated plugin, we highly recommend downloading the latest version. It not only resolves the previous issues but also introduces exciting new features that we're sure you'll love.

Now, for a lighthearted moment during this long journey, here's a joke for you:

Why did the plugin's update take forever?

Because it was caught in a time warp, trying to perfect its dance moves!
:dancer: :dancing_men: :man_dancing: :dancers: :dancing_women: :dancer: :dancing_men: :man_dancing: :dancers: :dancing_women:

We hope this joke brings a chuckle and adds a touch of humor to the lengthy update process. Thank you again for your understanding and patience. If you have any further questions or need assistance, please don't hesitate to reach out.

Thank you for your unwavering support, and we're thrilled to have you as a valued user of our plugin. Enjoy the new and improved version!

--
Best regards,
Yaroslav Borodii
